# Generated by Django 3.2.13 on 2022-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100)),
                ('createon', models.DateTimeField(auto_now_add=True)),
                ('modifedon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
